name: demo-flutter
version: git
summary: Demo Flutter Application
description: |
  A demonstration Flutter application for Linux Desktop.
  This package provides a simple counter application built with Flutter,
  showcasing cross-platform development capabilities.

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
    build-for: amd64

apps:
  demo-flutter:
    command: bin/demo_flutter
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback
      - network
      - home

parts:
  demo-flutter:
    plugin: dump
    source: build/linux/x64/release/bundle
    organize:
      '*': bin/
    stage-packages:
      - libgtk-3-0
      - libglib2.0-0
      - libgcc-s1
      - libc6
    build-packages:
      - gcc

  desktop-file:
    plugin: dump
    source: .
    override-build: |
      # Create desktop file
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      
      cat > $SNAPCRAFT_PART_INSTALL/usr/share/applications/demo-flutter.desktop << EOF
      [Desktop Entry]
      Type=Application
      Name=Demo Flutter
      Comment=Demo Flutter Application
      Exec=demo-flutter
      Icon=\${SNAP}/usr/share/icons/hicolor/256x256/apps/demo-flutter.png
      Categories=Development;Utility;
      StartupNotify=true
      EOF
      
      # Copy icon if available
      if [ -f "web/icons/Icon-512.png" ]; then
        cp web/icons/Icon-512.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/demo-flutter.png
      else
        # Create a simple placeholder icon
        echo "Creating placeholder icon..."
        touch $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/demo-flutter.png
      fi
